### ISSUE TITLE
EmulationStation and others

### ISSUE THREAD

**Issue by MaXGitteR** [gameblabla/retrostone2-buildroot#6]
Maybe add emulationstation.org (or Retroarch ...) and a choise to choose if you want to boot to terminal, EmulationStation or gmenu2x or ...

**Comment by gameblabla** [comment]
If you put a autoexec.sh script file at the root of your NTFS partition, it will execute whatever is inside. (could be emulationstation, retroarch...)
I do not intend on porting EmulationStation myself (most notably the lack of OPK support, which completely rules it out) but others could do it.
